load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "ClockManager",
    srcs = ["ClockManager.cpp"],
    hdrs = ["ClockManager.h"],
    deps = ["//Code/DataStore:DataStore"],
)