load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "DataStore",
    srcs = ["DataStore.cpp"],
    hdrs = ["DataStore.h"],
    deps = ["//Code/Type:Type", "//Code/local:local"],
)