load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "DoubleReader",
    srcs = ["DoubleReader.cpp"],
    hdrs = ["DoubleReader.h"],
    deps = ["//Code/Reader:Reader", "//Code/DoubleType:DoubleType"],
)
