load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ImageType",
    srcs = ["ImageType.h"], 
    deps = ["//Code/main:opencv", "//Code/Type:Type"],
)